const express = require('express')
const router = express.Router()

router.use('/account', require('./account'))
router.use('/accountlink', require('./accountlink'))
router.use('/bbaccount', require('./bbaccount'))
router.use('/bbcash', require('./bbcash'))
router.use('/bbrp', require('./bbrp'))
router.use('/cash_transfer', require('./cash_transfer'))
router.use('/cashin', require('./cashin'))
router.use('/cashout', require('./cashout'))
router.use('/fix_asset', require('./fix_asset'))
router.use('/fix_asset_group', require('./fix_asset_group'))
router.use('/generaljournal', require('./generaljournal'))
router.use('/generalledger', require('./generalledger'))
router.use('/generalledgerperiod', require('./generalledgerperiod'))
router.use('/giroin', require('./giroin'))
router.use('/giroout', require('./giroout'))
router.use('/inventoryadj', require('./inventoryadj'))
router.use('/inventorybb', require('./inventorybb'))
router.use('/inventoryin', require('./inventoryin'))
router.use('/inventoryout', require('./inventoryout'))
router.use('/inventorystockchange', require('./inventorystockchange'))
router.use('/inventorystocktransfer', require('./inventorystocktransfer'))
router.use('/reconciliation_adj', require('./reconciliation_adj'))
router.use('/reconciliation_bank', require('./reconciliation_bank'))

module.exports = router